/// Flutter icons CardsIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CardsIcons
///      fonts:
///       - asset: fonts/CardsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CardsIcons {
  CardsIcons._();

  static const _kFontFam = 'CardsIcons';
  static const String? _kFontPkg = null;

  static const IconData carreau = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coeur = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pique = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trefle = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
