/// Flutter icons MagicianIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MagicianIcons
///      fonts:
///       - asset: fonts/MagicianIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MagicianIcons {
  MagicianIcons._();

  static const _kFontFam = 'MagicianIcons';
  static const String? _kFontPkg = null;

  static const IconData camera = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardselector = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crop = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discard = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotatecamera = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotateimage = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
